### ISSUE TITLE
zh-cn/zh-tw: Issues with QA tags

### ISSUE THREAD

**Issue by fsundermeyer** [doc-suse-com/l10n#12]
Overlapping number and text in strings with &lt;question> tags for zh-CN and zh-TW. Translators believe it is coming from zh_cn.xml and zh_tw.xml and the tag in question appears to be  &lt;l:template name="qandaentry" text=" or &lt;l:template name="question" text="

![image](https://user-images.githubusercontent.com/1872885/132538845-11083d56-7dfb-4f82-8674-d758b8f0a5e4.png)

![image](https://user-images.githubusercontent.com/1872885/132538890-98fa92ac-6a92-46fb-affd-9e1a9f69b45e.png)

**Comment by ghost** [comment]
Item 1 from this old Japanese issue appears to be related: https://github.com/openSUSE/suse-xsl/issues/414

**Comment by ghost** [comment]
~~ptinley-vt The DOCX with the bug reports we got was incomplete regarding the problematic strings. Can you or someone else from VT help out please?~~ Actually forget about it, sorry. I think this is not actually related to those translations themselves.

**Comment by janajaeger** [comment]
Check whether this also concerns Japanese.

**Comment by ptinley-vt** [comment]
Looking at the PDFs I produced in July, it does effect **Japanese**, do a small degree. The alignment is not ideal. I would say that if there are less that 10 questions it could be considered passable. Notice that there is no space number with full-stop and the text of the paragraph.

![image](https://user-images.githubusercontent.com/68334239/193851337-1bc98474-d581-40ef-9b9c-f12ee55db9e5.png)

Looking at the published file on https://documentation.suse.com/ja-jp/sled/15-SP4/pdf/book-administration_color_ja.pdf it seems that the issue has been resolved by increasing the indent.

**S. Chinese.** On the July PDF the number is up against the paragraph text, as with Japanese.

![image](https://user-images.githubusercontent.com/68334239/193853178-aec03bd6-301a-45aa-93d5-9443fc7e3fe5.png)

**T. Chinese.** On the July PDF the number is overlaid by the paragraph text. 

However, checking the currently published files I can see that these are now fine; indented more and the equivalent of "Q" character has been removed.

**Comment by jfaltenbacher** [comment]
@ptinley-vt please check with current SLE 15 SP5 loc drop if the issue still occurs

**Comment by ptinley-vt** [comment]
Confirming that this issue does not occur in SLE 15 SP5 (locdrop 2), SLES and SLED Administration Guide of S. Chinese, T. Chinese and Japanese. Refer to section 10.9. The questions (Q) and answers (A) are not numbered so there is enough room, and no overlapping.

**Comment by jfaltenbacher** [comment]
thank you @ptinley-vt for checking. 
Closing this issue as fixed.
