### ISSUE TITLE
Typo in German translations: stelln -> stellen

### ISSUE THREAD

**Issue by taroth21** [doc-suse-com/l10n#2]
`Sie lernen, wie Sie die Installation steuern, Installationsmedien zur Verfügung stelln und mit normalen Methoden booten können.` (deployment_prep_aarch64.xml, deployment_prep_x86.xml)

We received a PR for fixing this (https://github.com/SUSE/doc-sle/pull/860). I fixed additional occurrences in another file and backported the changes to the German translations of all Code 15 doc versions. 

This needs to be fixed in the TM.

**Comment by jfaltenbacher** [comment]
Request to correct TM send to Vistatec

**Comment by jfaltenbacher** [comment]
vistatec reported that they have fixed this in the TM

**Comment by ghost** [comment]
-> Closed then.
